Traceback (most recent call last):
  File "/home/mkarttu/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mkarttu/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mkarttu/.local/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#import sys
#sys.path.append('./helpers')

#from helpers import settings
#import settings

###
from myst_nb import glue
from IPython.display import IFrame
from IPython.display import Markdown
# Additional styling ; should be moved into helpers
from IPython.core.display import display, HTML
HTML('<style>{}</style>'.format(open('styler.css').read()))
#import pandas as pd
from datetime import datetime
from IPython.display import Markdown as md
updated = datetime.now()
now = updated.strftime("%A, %B %d %Y at %H:%M" )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-e341d7124aec>[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;31m# Additional styling ; should be moved into helpers[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;32mfrom[0m [0mIPython[0m[0;34m.[0m[0mcore[0m[0;34m.[0m[0mdisplay[0m [0;32mimport[0m [0mdisplay[0m[0;34m,[0m [0mHTML[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m [0mHTML[0m[0;34m([0m[0;34m'<style>{}</style>'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mopen[0m[0;34m([0m[0;34m'styler.css'[0m[0;34m)[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m [0;31m#import pandas as pd[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m [0;32mfrom[0m [0mdatetime[0m [0;32mimport[0m [0mdatetime[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'styler.css'
FileNotFoundError: [Errno 2] No such file or directory: 'styler.css'

